language: csharp
sudo: required
distro: xenial
mono: none
dotnet: 3.0.101

services:
  - docker

before_script:
  - chmod -R a+x scripts
script:
  - ./scripts/docker-push.sh
notifications:
  email:
    on_success: never
    on_failure: always
